### ISSUE TITLE
Como usuario de Spotify quiero buscar una canción de un artista específico para manipular un fondo dinámico de colores combinados basado en las características de la canción

### ISSUE THREAD

**Issue by JorgeRamirezAnzaldo** [djonguitud/synesthesia-project#51]
Criterios de aceptación:

Cuando presiono el botón de Buscar, se hace una petición a la API de Spotify que trae las características de "energy" y "valence" de la canción. El valor de "energy" corresponde a la medida perceptiva de intensidad y actividad. Mientras que el valor de "valence" describe la positividad musical de la canción.

Cuando presiono el botón de Buscar, se utilizan los datos de energy y valence de la canción para generar un fondo dinámico de colores:
    * Se utiliza un arreglo de cuatro colores para formar el fondo dinámico: amarillo, azul, rojo y magenta.
    * El valor de energy define la proporción de rojo y magenta.
    * El valor de valence define la proporción de amarillo azul.
  
Cuando se muestra el fondo dinámico de colores y el usuario presiona algún botón de color, entonces el fondo dinámico de colores agrega dos tonos del color seleccionado por el usuario al arreglo de colores para aumentar la presencia del color deseado.

**Comment by maugh108** [comment]
trackscript.js
gradient.js
